services:
  api:
    container_name: apieasier_api
    hostname: apieasier_api
    restart: always
    ports:
      - "5240:8080"
    image: apieasier_api
    build:
      context: ./src/ApiEasier.Api/.
      dockerfile: Dockerfile
    volumes:
      - ./configs:/app/configuration
    env_file:
      - path: ./environment/default.env
        required: true
    networks:
      - backend
  mongodb:
    image: mongo:4.4
    hostname: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - backend


networks:
  backend:
    external: false
    driver: bridge
