services:
  api:
    container_name: apieasier_api
    hostname: apieasier_api
    restart: always
    ports:
      - "5239:8080"
    volumes:
        - ./configuration:./configuration
    depends_on:
      mongodb:
        condition: service_healthy
        restart: true
    image: apieasier_api
    build:
      context: ./ApiEasier.Server/.
      dockerfile: Dockerfile
    env_file:
      - path: ./environment/default.env
        required: true
    networks:
      - backend
  mongodb:
    image: mongo:6.0.20-jammy
    hostname: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    networks:
      - backend
    

networks:
  backend:
    external: false
    driver: bridge
