services:
  api:
    container_name: apieasier_api
    hostname: apieasier_api
    restart: always
    ports:
      - "5240:8080"
    image: apieasier_api
    build:
      context: ./src 
      dockerfile: ApiEasier.Api/Dockerfile
    volumes:
      - ./configs:/app/ApiConfigurations
    env_file:
      - path: ./environment/default.env
        required: true
    networks:
      - backend
  mongodb:
    image: mongo:4.4
    hostname: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - backend
  frontend:
    container_name: apieasier_frontend
    hostname: apieasier_frontend
    restart: always
    ports:
      - "5280:80"
    image: apieasier_frontend
    build:
      context: ./ApiEasier.Frontend/
      dockerfile: Dockerfile


networks:
  backend:
    external: false
    driver: bridge
